import * as d3 from 'd3';
import * as d3Axis from 'd3-axis';
export declare class CanvasDataPlot {
    parent: d3.Selection<any, {}, HTMLElement, {}>;
    canvasDimensions: Array<number>;
    config: CanvasDataPlot.Config;
    data: Array<Array<[number, number]>>;
    dataIDs: Array<string>;
    dataLabels: Array<String>;
    displayIndexStart: Array<number>;
    displayIndexEnd: Array<number>;
    dataColors: Array<string>;
    xAxisLabelText: string;
    yAxisLabelText: string;
    updateViewCallback: undefined;
    disableLegend: boolean;
    invertYAxis: boolean;
    gridColor: string;
    markerLineWidth: number;
    markerRadius: number;
    xTicksPerPixel: number;
    yTicksPerPixel: number;
    minCanvasWidth: number;
    minCanvasHeight: number;
    legendMargin: number;
    legendXPadding: number;
    legendYPadding: number;
    legendLineHeight: number;
    margin: CanvasDataPlot.PlotMargins;
    showToolstips: boolean;
    tooltipRadiusSquared: number;
    totalWidth: number;
    totalHeight: number;
    width: number;
    legendWidth: number;
    height: number;
    zoomListener: any;
    div: d3.Selection<any, {}, any, {}>;
    d3Canvas: d3.Selection<any, {}, any, {}>;
    canvas: CanvasRenderingContext2D;
    svg: d3.Selection<any, {}, any, {}>;
    svgTranslateGroup: d3.Selection<any, {}, any, {}>;
    xScale: d3Axis.AxisScale<any>;
    yScale: d3Axis.AxisScale<number>;
    xAxis: d3Axis.Axis<number>;
    yAxis: d3Axis.Axis<number>;
    xAxisLabel: d3.Selection<SVGTextElement, {}, any, {}>;
    yAxisLabel: d3.Selection<SVGTextElement, {}, any, {}>;
    yAxisGroup: d3.Selection<any, {}, any, {}>;
    xAxisGroup: d3.Selection<any, {}, any, {}>;
    tooltip: d3.Selection<any, {}, any, {}>;
    legend: any;
    legendBG: any;
    showTooltips: boolean;
    xAxisZoom: boolean;
    yAxisZoom: boolean;
    constructor(parentElement: d3.Selection<any, {}, HTMLElement, {}>, canvasDimensions: Array<number>, config?: CanvasDataPlot.Config);
    zoomFunction(): void;
    addDataSet(uniqueID?: string, label?: string, dataSet?: Array<[number, number]>, colorString?: string, updateDomains?: boolean, copyData?: boolean): void;
    addDataPoint(uniqueID?: string, dataPoint?: [number, number], updateDomains?: boolean, copyData?: boolean): void;
    removeDataSet(uniqueID: string): void;
    setZoomXAxis(zoomX: boolean): void;
    setZoomYAxis(zoomY: boolean): void;
    resize(dimensions: Array<number>): void;
    updateDomains(xDomain: Array<number>, yDomain: Array<number>, makeItNice: boolean): void;
    getXDomain(): Array<number>;
    getYDomain(): Array<number>;
    calculateXDomain(): Array<number>;
    calculateYDomain(): Array<number>;
    destroy(): void;
    setupXScaleAndAxis(): void;
    setupYScaleAndAxis(): void;
    getDataID(index: number): string;
    updateTooltip(): void;
    getTooltipStringX(dataPoint: [number, number]): string;
    getTooltipStringY(dataPoint: [number, number]): string;
    showTooltip(position: Array<number>, color: string, xText: string, yText: string): void;
    removeTooltip(): void;
    updateLegend(): void;
    findLargestSmaller(d: Array<Array<number>>, ia: number, ib: number, v: number): number;
    updateDisplayIndices(): void;
    redrawCanvasAndAxes(): void;
    drawCanvas(): void;
    drawGrid(): void;
    drawDataSet(dataIndex: number): void;
    resetZoomListenerAxes(): void;
    updateZoomValues(scale: number, translate: number): void;
    CanvasPlot_shallowObjectCopy(inObj: any): any;
    CanvasPlot_appendToObject(obj: any, objToAppend: any): void;
}
export declare namespace CanvasDataPlot {
    interface Config {
        xAxisLabel?: string;
        yAxisLabel?: string;
        markerLineWidth?: number;
        markerRadius?: number;
        updateViewCallback?: undefined;
        disableLegend?: boolean;
        invertYAxis?: boolean;
        gridColor?: string;
        xTicksPerPixel?: number;
        yTicksPerPixel?: number;
        minCanvasWidth?: number;
        minCanvasHeight?: number;
        legendMargin?: number;
        legendXPadding?: number;
        legendYPadding?: number;
        legendLineHeight?: number;
        plotMargins?: PlotMargins;
        showToolstips?: boolean;
        hasOwnProperty?(prop: string): boolean;
        tooltipRadius?: number;
        plotLineWidth?: number;
        maxInformationDensity?: number;
        showMarkerDensity?: number;
    }
    interface PlotMargins {
        top?: number;
        right?: number;
        bottom?: number;
        left?: number;
    }
}
